name: Bartian Creative
year: 2023
# Essential information for Admin CMS to work
repo: bradeneast/bartiancreative
status_badge_url: https://api.netlify.com/api/v1/badges/c9bdfd0b-770d-4ce5-b695-e1d0c972226a/deploy-status